# Linux Toolkit Scripts Configuration
# This file defines the available scripts and their categories

# Example structure:

# [scripts]

# [scripts.network]
# name = "Network Security"
# description = "Network analysis and security tools"
# directory = "network"

# [[scripts.network.commands]]
# name = "Port Scanner"
# description = "Scan for open ports on a target host"
# script = "port_scan.sh"
# usage = "port_scan.sh <target_host> [start_port] [end_port]"
# requires_sudo = false
# tags = ["network", "security", "scanning"]

[scripts]

[scripts.system]
name = "System Utilities"
description = "General system utilities and maintenance scripts"
directory = "system"

[[scripts.system.commands]]
name = "Update and Upgrade System"
description = "Update and upgrade installed packages"
script = "update_upgrade.sh"
usage = "update_upgrade.sh"
requires_sudo = true
tags = ["system", "maintenance", "updates"]

[scripts.network]
name = "Network Security"
description = "Network analysis and security tools"
directory = "network"

[[scripts.network.commands]]
name = "Port Scanner"
description = "See what ports are currently active on the system."
script = "active_ports.sh"
usage = "active_ports.sh"
requires_sudo = true
tags = ["network", "security", "ports", "active"]

[[scripts.network.commands]]
name = "Enable Firewall"
description = "Enable and configure the Uncomplicated Firewall (UFW)."
script = "enable_firewall.sh"
usage = "enable_firewall.sh"
requires_sudo = true
tags = ["network", "security", "firewall", "ufw"]

[[scripts.network.commands]]
name = "Secure SSH"
description = "Secure the SSH service."
script = "secure_ssh.sh"
usage = "secure_ssh.sh"
requires_sudo = true
tags = ["network", "security", "firewall", "ufw"]

[scripts.install]
name = "Installation Scripts"
description = "Scripts for installing and configuring software"
directory = "install"

[[scripts.install.commands]]
name = "Install Node.js"
description = "Install Node.js via NVM."
script = "install_nodejs.sh"
usage = "install_nodejs.sh"
requires_sudo = true
tags = ["install", "nodejs", "management"]